name: Build and deploy Python app to Azure Web App - busqueda-candidatos-rrhh-ub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          mkdir deploy
          copy app.py deploy\
          copy requirements.txt deploy\
          copy web.config deploy\  # ← si no lo tienes, te puedo generar uno
          xcopy config deploy\config /E /I
          xcopy controllers deploy\controllers /E /I
          xcopy routes deploy\routes /E /I
          xcopy utils deploy\utils /E /I

      - name: Create ZIP package
        run: |
          cd deploy
          powershell Compress-Archive -Path * -DestinationPath ../python-app.zip
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: python-app.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_NUEVO }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_NUEVO }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_NUEVO }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'busqueda-candidatos-rrhh-ub'
          package: python-app.zip
          type: zip
          clean: true
          restart: true
          slot-name: production
