name: Build and deploy Python app to Azure Web App - busqueda-candidatos-rrhh-ub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Empaquetar proyecto sin carpetas innecesarias
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "*.zip"

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Esperar para evitar conflicto de reinicio
        run: sleep 30

      - name: Login a Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_85C63E05B2DD488892E86993B27E9C48 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17EA177940FA4D428D4B0242C97B4156 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_52C05E71143448CEBA3131777DBB5458 }}


      - name: Esperar 60s para estabilizar contenedor
        run: sleep 60


      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'busqueda-candidatos-rrhh-ub'
          slot-name: 'Production'
          package: 'release.zip'
