name: Build and deploy Python app to Azure Web App - api-busqueda-candidatos-ub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp app.py deploy/
          cp requirements.txt deploy/
          cp web.config deploy/
          cp -r config deploy/
          cp -r controllers deploy/
          cp -r routes deploy/
          cp -r utils deploy/
          # Si tienes archivos como .env, templates/, static/, agrégalos aquí

      - name: Create ZIP package
        run: |
          cd deploy
          zip -r ../python-app.zip * .[^.]* || true
          cd ..

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: python-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip python-app.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_44BBEA52D37A456CBBC044A5E8F3966C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF504608B3A2474BBCBA159C6FACC7C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69ABCD326F3B49B58C6D8F754061F9B0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-busqueda-candidatos-ub'
          package: .
          type: zip
          clean: true
          restart: true
